version: "3"

services:
  distro:
    image: alpine
    restart: always
    container_name: custome-alpine
    entrypoint: tail -f /dev/null

  databases:
    image: postgres:latest
    restart: always
    container_name: postgress-db
    environment:
      - POSTGRES_PASSWORD=superpass
    ports:
      - "5432:5432"
    volumes:
      - ../dump:/tmp/

  web:
    image: nginx
    restart: always
    container_name: nginx_web
    ports:
      - "8081:80"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=sample.com
      - NGINX_port=80
    links:
      - databases:db
      - distro

volumes:
  data:
    external: true